// Mocks generated by Mockito 5.4.6 from annotations
// in lystra/test/ui/features/lists/lists_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:lystra/data/repositories/auth_repository.dart' as _i7;
import 'package:lystra/data/repositories/list_entry_repository.dart' as _i8;
import 'package:lystra/data/repositories/shopping_list_repository.dart' as _i5;
import 'package:lystra/domain/models/app_user.dart' as _i3;
import 'package:lystra/domain/models/list_entry.dart' as _i4;
import 'package:lystra/domain/models/shopping_list.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShoppingList_0 extends _i1.SmartFake implements _i2.ShoppingList {
  _FakeShoppingList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppUser_1 extends _i1.SmartFake implements _i3.AppUser {
  _FakeAppUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListEntry_2 extends _i1.SmartFake implements _i4.ListEntry {
  _FakeListEntry_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShoppingListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListRepository extends _i1.Mock
    implements _i5.ShoppingListRepository {
  MockShoppingListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.ShoppingList>> getLists(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [uid],
        ),
        returnValue:
            _i6.Future<List<_i2.ShoppingList>>.value(<_i2.ShoppingList>[]),
      ) as _i6.Future<List<_i2.ShoppingList>>);

  @override
  _i6.Future<_i2.ShoppingList> createList(
    String? uid,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [
            uid,
            name,
          ],
        ),
        returnValue: _i6.Future<_i2.ShoppingList>.value(_FakeShoppingList_0(
          this,
          Invocation.method(
            #createList,
            [
              uid,
              name,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ShoppingList>);

  @override
  _i6.Future<void> updateList(
    String? uid,
    _i2.ShoppingList? list,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [
            uid,
            list,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> archiveList(
    String? uid,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveList,
          [
            uid,
            listId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteList(
    String? uid,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [
            uid,
            listId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.AppUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i3.AppUser?>.empty(),
      ) as _i6.Stream<_i3.AppUser?>);

  @override
  _i6.Future<_i3.AppUser> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i3.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i3.AppUser>);

  @override
  _i6.Future<_i3.AppUser> registerWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i6.Future<_i3.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #registerWithEmail,
            [
              email,
              password,
              displayName,
            ],
          ),
        )),
      ) as _i6.Future<_i3.AppUser>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ListEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListEntryRepository extends _i1.Mock
    implements _i8.ListEntryRepository {
  MockListEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.ListEntry>> getEntries(
    String? uid,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntries,
          [
            uid,
            listId,
          ],
        ),
        returnValue: _i6.Future<List<_i4.ListEntry>>.value(<_i4.ListEntry>[]),
      ) as _i6.Future<List<_i4.ListEntry>>);

  @override
  _i6.Future<_i4.ListEntry> addEntry(
    String? uid,
    String? listId,
    String? itemId, {
    double? quantity = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [
            uid,
            listId,
            itemId,
          ],
          {#quantity: quantity},
        ),
        returnValue: _i6.Future<_i4.ListEntry>.value(_FakeListEntry_2(
          this,
          Invocation.method(
            #addEntry,
            [
              uid,
              listId,
              itemId,
            ],
            {#quantity: quantity},
          ),
        )),
      ) as _i6.Future<_i4.ListEntry>);

  @override
  _i6.Future<void> toggleEntry(
    String? uid,
    String? listId,
    String? entryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleEntry,
          [
            uid,
            listId,
            entryId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateQuantity(
    String? uid,
    String? listId,
    String? entryId,
    double? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            uid,
            listId,
            entryId,
            quantity,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeEntry(
    String? uid,
    String? listId,
    String? entryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeEntry,
          [
            uid,
            listId,
            entryId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetEntries(
    String? uid,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetEntries,
          [
            uid,
            listId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void invalidateCache(String? listId) => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [listId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateAll() => super.noSuchMethod(
        Invocation.method(
          #invalidateAll,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
