// Mocks generated by Mockito 5.4.6 from annotations
// in lystra/test/ui/features/history/history_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:lystra/data/repositories/auth_repository.dart' as _i6;
import 'package:lystra/data/repositories/purchase_record_repository.dart'
    as _i4;
import 'package:lystra/domain/models/app_user.dart' as _i3;
import 'package:lystra/domain/models/purchase_record.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePurchaseRecord_0 extends _i1.SmartFake
    implements _i2.PurchaseRecord {
  _FakePurchaseRecord_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppUser_1 extends _i1.SmartFake implements _i3.AppUser {
  _FakeAppUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PurchaseRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseRecordRepository extends _i1.Mock
    implements _i4.PurchaseRecordRepository {
  MockPurchaseRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.PurchaseRecord>> getRecords(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecords,
          [uid],
        ),
        returnValue:
            _i5.Future<List<_i2.PurchaseRecord>>.value(<_i2.PurchaseRecord>[]),
      ) as _i5.Future<List<_i2.PurchaseRecord>>);

  @override
  _i5.Future<_i2.PurchaseRecord> createRecord(
    String? uid,
    _i2.PurchaseRecord? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRecord,
          [
            uid,
            record,
          ],
        ),
        returnValue: _i5.Future<_i2.PurchaseRecord>.value(_FakePurchaseRecord_0(
          this,
          Invocation.method(
            #createRecord,
            [
              uid,
              record,
            ],
          ),
        )),
      ) as _i5.Future<_i2.PurchaseRecord>);

  @override
  _i5.Future<void> deleteRecord(
    String? uid,
    String? recordId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [
            uid,
            recordId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.AppUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i3.AppUser?>.empty(),
      ) as _i5.Stream<_i3.AppUser?>);

  @override
  _i5.Future<_i3.AppUser> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.AppUser>);

  @override
  _i5.Future<_i3.AppUser> registerWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i5.Future<_i3.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #registerWithEmail,
            [
              email,
              password,
              displayName,
            ],
          ),
        )),
      ) as _i5.Future<_i3.AppUser>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
