// Mocks generated by Mockito 5.4.6 from annotations
// in lystra/test/data/repositories/item_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:lystra/data/services/firestore_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_2<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_3<T extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Map<String, dynamic>> userCollection(
    String? uid,
    String? sub,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userCollection,
          [
            uid,
            sub,
          ],
        ),
        returnValue: _FakeCollectionReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #userCollection,
            [
              uid,
              sub,
            ],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> userDoc(
    String? uid,
    String? sub,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userDoc,
          [
            uid,
            sub,
            id,
          ],
        ),
        returnValue: _FakeDocumentReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #userDoc,
            [
              uid,
              sub,
              id,
            ],
          ),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>> getDoc(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoc,
          [path],
        ),
        returnValue:
            _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_2<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDoc,
            [path],
          ),
        )),
      ) as _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getCollection(
          String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollection,
          [path],
        ),
        returnValue: _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
            _FakeQuerySnapshot_3<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getCollection,
            [path],
          ),
        )),
      ) as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<void> setDoc(
    String? path,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDoc,
          [
            path,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DocumentReference<Map<String, dynamic>>> addDoc(
    String? collectionPath,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDoc,
          [
            collectionPath,
            data,
          ],
        ),
        returnValue:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #addDoc,
            [
              collectionPath,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>);

  @override
  _i4.Future<void> updateDoc(
    String? path,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDoc,
          [
            path,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDoc(String? path) => (super.noSuchMethod(
        Invocation.method(
          #deleteDoc,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i2.QuerySnapshot<Map<String, dynamic>>> streamCollection(
          String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCollection,
          [path],
        ),
        returnValue:
            _i4.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Stream<_i2.DocumentSnapshot<Map<String, dynamic>>> streamDoc(
          String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamDoc,
          [path],
        ),
        returnValue:
            _i4.Stream<_i2.DocumentSnapshot<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<_i2.DocumentSnapshot<Map<String, dynamic>>>);
}
