// Mocks generated by Mockito 5.4.6 from annotations
// in lystra/test/ui/features/shopping/shopping_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:lystra/data/repositories/auth_repository.dart' as _i12;
import 'package:lystra/data/repositories/category_repository.dart' as _i14;
import 'package:lystra/data/repositories/item_repository.dart' as _i11;
import 'package:lystra/data/repositories/list_entry_repository.dart' as _i8;
import 'package:lystra/data/repositories/purchase_record_repository.dart'
    as _i13;
import 'package:lystra/data/repositories/shopping_list_repository.dart' as _i10;
import 'package:lystra/domain/models/app_user.dart' as _i5;
import 'package:lystra/domain/models/category.dart' as _i7;
import 'package:lystra/domain/models/item.dart' as _i4;
import 'package:lystra/domain/models/list_entry.dart' as _i2;
import 'package:lystra/domain/models/purchase_record.dart' as _i6;
import 'package:lystra/domain/models/shopping_list.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListEntry_0 extends _i1.SmartFake implements _i2.ListEntry {
  _FakeListEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShoppingList_1 extends _i1.SmartFake implements _i3.ShoppingList {
  _FakeShoppingList_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItem_2 extends _i1.SmartFake implements _i4.Item {
  _FakeItem_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppUser_3 extends _i1.SmartFake implements _i5.AppUser {
  _FakeAppUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchaseRecord_4 extends _i1.SmartFake
    implements _i6.PurchaseRecord {
  _FakePurchaseRecord_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_5 extends _i1.SmartFake implements _i7.Category {
  _FakeCategory_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ListEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListEntryRepository extends _i1.Mock
    implements _i8.ListEntryRepository {
  MockListEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i2.ListEntry>> getEntries(
    String? uid,
    String? listId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntries,
          [
            uid,
            listId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<List<_i2.ListEntry>>.value(<_i2.ListEntry>[]),
      ) as _i9.Future<List<_i2.ListEntry>>);

  @override
  _i9.Future<_i2.ListEntry> addEntry(
    String? uid,
    String? listId,
    String? itemId, {
    double? quantity = 1.0,
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [
            uid,
            listId,
            itemId,
          ],
          {
            #quantity: quantity,
            #householdId: householdId,
          },
        ),
        returnValue: _i9.Future<_i2.ListEntry>.value(_FakeListEntry_0(
          this,
          Invocation.method(
            #addEntry,
            [
              uid,
              listId,
              itemId,
            ],
            {
              #quantity: quantity,
              #householdId: householdId,
            },
          ),
        )),
      ) as _i9.Future<_i2.ListEntry>);

  @override
  _i9.Future<void> toggleEntry(
    String? uid,
    String? listId,
    String? entryId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleEntry,
          [
            uid,
            listId,
            entryId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateQuantity(
    String? uid,
    String? listId,
    String? entryId,
    double? quantity, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            uid,
            listId,
            entryId,
            quantity,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeEntry(
    String? uid,
    String? listId,
    String? entryId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeEntry,
          [
            uid,
            listId,
            entryId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> resetEntries(
    String? uid,
    String? listId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetEntries,
          [
            uid,
            listId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i2.ListEntry>> watchEntries(
    String? uid,
    String? listId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchEntries,
          [
            uid,
            listId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Stream<List<_i2.ListEntry>>.empty(),
      ) as _i9.Stream<List<_i2.ListEntry>>);

  @override
  void invalidateCache(String? listId) => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [listId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateAll() => super.noSuchMethod(
        Invocation.method(
          #invalidateAll,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShoppingListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListRepository extends _i1.Mock
    implements _i10.ShoppingListRepository {
  MockShoppingListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i3.ShoppingList>> getLists(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [uid],
        ),
        returnValue:
            _i9.Future<List<_i3.ShoppingList>>.value(<_i3.ShoppingList>[]),
      ) as _i9.Future<List<_i3.ShoppingList>>);

  @override
  _i9.Future<_i3.ShoppingList> createList(
    String? uid,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [
            uid,
            name,
          ],
        ),
        returnValue: _i9.Future<_i3.ShoppingList>.value(_FakeShoppingList_1(
          this,
          Invocation.method(
            #createList,
            [
              uid,
              name,
            ],
          ),
        )),
      ) as _i9.Future<_i3.ShoppingList>);

  @override
  _i9.Future<List<_i3.ShoppingList>> getHouseholdLists(String? householdId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHouseholdLists,
          [householdId],
        ),
        returnValue:
            _i9.Future<List<_i3.ShoppingList>>.value(<_i3.ShoppingList>[]),
      ) as _i9.Future<List<_i3.ShoppingList>>);

  @override
  _i9.Future<_i3.ShoppingList> createHouseholdList(
    String? householdId,
    String? uid,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHouseholdList,
          [
            householdId,
            uid,
            name,
          ],
        ),
        returnValue: _i9.Future<_i3.ShoppingList>.value(_FakeShoppingList_1(
          this,
          Invocation.method(
            #createHouseholdList,
            [
              householdId,
              uid,
              name,
            ],
          ),
        )),
      ) as _i9.Future<_i3.ShoppingList>);

  @override
  _i9.Future<void> updateList(
    String? uid,
    _i3.ShoppingList? list,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [
            uid,
            list,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> archiveList(
    String? uid,
    String? listId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveList,
          [
            uid,
            listId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteList(
    String? uid,
    String? listId, {
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [
            uid,
            listId,
          ],
          {#householdId: householdId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateHouseholdCache(String? householdId) => super.noSuchMethod(
        Invocation.method(
          #invalidateHouseholdCache,
          [householdId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i11.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i4.Item>> getItems(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getItems,
          [uid],
        ),
        returnValue: _i9.Future<List<_i4.Item>>.value(<_i4.Item>[]),
      ) as _i9.Future<List<_i4.Item>>);

  @override
  List<_i4.Item> filter(
    List<_i4.Item>? items, {
    String? categoryId,
    String? query = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filter,
          [items],
          {
            #categoryId: categoryId,
            #query: query,
          },
        ),
        returnValue: <_i4.Item>[],
      ) as List<_i4.Item>);

  @override
  _i9.Future<_i4.Item> createItem(
    String? uid,
    String? name,
    String? categoryId, {
    String? unit = 'un',
    String? emoji,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createItem,
          [
            uid,
            name,
            categoryId,
          ],
          {
            #unit: unit,
            #emoji: emoji,
          },
        ),
        returnValue: _i9.Future<_i4.Item>.value(_FakeItem_2(
          this,
          Invocation.method(
            #createItem,
            [
              uid,
              name,
              categoryId,
            ],
            {
              #unit: unit,
              #emoji: emoji,
            },
          ),
        )),
      ) as _i9.Future<_i4.Item>);

  @override
  _i9.Future<void> updateItem(
    String? uid,
    _i4.Item? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [
            uid,
            item,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteItem(
    String? uid,
    String? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [
            uid,
            itemId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<_i5.AppUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i9.Stream<_i5.AppUser?>.empty(),
      ) as _i9.Stream<_i5.AppUser?>);

  @override
  _i9.Future<_i5.AppUser> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<_i5.AppUser>.value(_FakeAppUser_3(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i5.AppUser>);

  @override
  _i9.Future<_i5.AppUser> registerWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i9.Future<_i5.AppUser>.value(_FakeAppUser_3(
          this,
          Invocation.method(
            #registerWithEmail,
            [
              email,
              password,
              displayName,
            ],
          ),
        )),
      ) as _i9.Future<_i5.AppUser>);

  @override
  _i9.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [PurchaseRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseRecordRepository extends _i1.Mock
    implements _i13.PurchaseRecordRepository {
  MockPurchaseRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i6.PurchaseRecord>> getRecords(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecords,
          [uid],
        ),
        returnValue:
            _i9.Future<List<_i6.PurchaseRecord>>.value(<_i6.PurchaseRecord>[]),
      ) as _i9.Future<List<_i6.PurchaseRecord>>);

  @override
  _i9.Future<_i6.PurchaseRecord> createRecord(
    String? uid,
    _i6.PurchaseRecord? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRecord,
          [
            uid,
            record,
          ],
        ),
        returnValue: _i9.Future<_i6.PurchaseRecord>.value(_FakePurchaseRecord_4(
          this,
          Invocation.method(
            #createRecord,
            [
              uid,
              record,
            ],
          ),
        )),
      ) as _i9.Future<_i6.PurchaseRecord>);

  @override
  _i9.Future<void> deleteRecord(
    String? uid,
    String? recordId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [
            uid,
            recordId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i14.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i7.Category>> getCategories(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [uid],
        ),
        returnValue: _i9.Future<List<_i7.Category>>.value(<_i7.Category>[]),
      ) as _i9.Future<List<_i7.Category>>);

  @override
  _i9.Future<_i7.Category> createCategory(
    String? uid,
    String? name,
    String? colorHex, {
    String? iconCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [
            uid,
            name,
            colorHex,
          ],
          {#iconCode: iconCode},
        ),
        returnValue: _i9.Future<_i7.Category>.value(_FakeCategory_5(
          this,
          Invocation.method(
            #createCategory,
            [
              uid,
              name,
              colorHex,
            ],
            {#iconCode: iconCode},
          ),
        )),
      ) as _i9.Future<_i7.Category>);

  @override
  _i9.Future<void> updateCategory(
    String? uid,
    _i7.Category? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            uid,
            category,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteCategory(
    String? uid,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [
            uid,
            categoryId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
